version: '3.8'

services:
  camera-server:
    build: .
    container_name: camera-server
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./recorder_temp:/app/recorder_temp
    restart: unless-stopped

networks:
  default:
    name: camera_network
